from django.test import TestCase, Client
from django.urls import reverse
from django.utils import timezone
from .models import Material, Kit, Checklist, ChecklistItem, LeituraQR
from django.contrib.auth import get_user_model

User = get_user_model()


class MaterialModelTests(TestCase):
    def test_material_creation_and_qr(self):
        m = Material.objects.create(
            nome='Teste', categoria='Cat', lote='123',
            data_esterilizacao=timezone.now().date(),
            status_esterilizacao='OK',
            validade=timezone.now().date(),
            responsavel='João', estoque=10
        )
        # codigo_qr should be generated by view, not model; here we simulate
        m.codigo_qr = f"MAT-{m.lote}-{m.nome}"
        m.save()
        self.assertEqual(str(m), 'Teste')


class ChecklistFlowTests(TestCase):
    def setUp(self):
        self.user = User.objects.create_user('testuser', 'a@b.com', 'pass')
        self.client = Client()
        self.client.login(username='testuser', password='pass')
        self.m1 = Material.objects.create(
            nome='Mat1', categoria='Cat', lote='L1',
            data_esterilizacao=timezone.now().date(), status_esterilizacao='OK',
            validade=timezone.now().date(), responsavel='X', estoque=5,
            codigo_qr='MAT-L1-Mat1'
        )
        self.kit = Kit.objects.create(nome='Kit1', lacre='LACRE1', codigo_qr='KIT-Kit1-1')
        self.kit.materiais.add(self.m1)

    def test_checklist_creation_generates_items(self):
        ck = Checklist.objects.create(kit=self.kit, fase='pre', conferido_por=self.user)
        # items created in view normally; manually simulate
        for mat in self.kit.materiais.all():
            ChecklistItem.objects.get_or_create(checklist=ck, material=mat)
        self.assertEqual(ChecklistItem.objects.filter(checklist=ck).count(), 1)

    def test_material_list_search_and_pagination(self):
        # create several materials to force pagination
        for i in range(30):
            Material.objects.create(
                nome=f'Mat{i}', categoria='Cat', lote=str(i),
                data_esterilizacao=timezone.now().date(), status_esterilizacao='OK',
                validade=timezone.now().date(), responsavel='X', estoque=5,
                codigo_qr=f'MAT-{i}'
            )
        url = reverse('lista_materiais')
        response = self.client.get(url + '?q=Mat1')
        self.assertEqual(response.status_code, 200)
        # should find at least Mat1 and Mat10, etc.
        self.assertContains(response, 'Mat1')
        # pagination first page should have 20 items
        self.assertIn('page_obj', response.context)
        self.assertEqual(response.context['page_obj'].paginator.per_page, 20)

    def test_checklist_create_view_sets_user(self):
        url = reverse('cadastrar_checklist')
        response = self.client.post(url, {
            'kit': self.kit.pk,
            'fase': 'pre',
            'paciente': 'P',
            'cirurgia': 'C'
        })
        # should redirect to list
        self.assertEqual(response.status_code, 302)
        ck = Checklist.objects.latest('id')
        self.assertEqual(ck.conferido_por, self.user)

    def test_scan_qr_marks_item(self):
        ck = Checklist.objects.create(kit=self.kit, fase='pre', conferido_por=self.user)
        for mat in self.kit.materiais.all():
            ChecklistItem.objects.get_or_create(checklist=ck, material=mat)
        url = reverse('scan_qr')
        response = self.client.post(url, data='{"codigo":"MAT-L1-Mat1"}', content_type='application/json')
        self.assertJSONEqual(response.content, {'success': True, 'tipo': 'material'})
        item = ChecklistItem.objects.get(checklist=ck, material=self.m1)
        self.assertTrue(item.conferido)
        self.assertEqual(LeituraQR.objects.filter(checklist=ck, material=self.m1, acao='conferido').count(), 1)
