# Generated by Django 5.2.12 on 2026-03-09 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('lacre', models.CharField(max_length=50)),
                ('codigo_qr', models.CharField(blank=True, max_length=200, unique=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('lote', models.CharField(max_length=50)),
                ('data_esterilizacao', models.DateField()),
                ('status_esterilizacao', models.CharField(choices=[('OK', 'OK'), ('pendente', 'Pendente'), ('reprocessar', 'Reprocessar')], default='OK', max_length=20)),
                ('validade', models.DateField()),
                ('responsavel', models.CharField(max_length=100)),
                ('estoque', models.PositiveIntegerField(default=0)),
                ('fornecedor', models.CharField(blank=True, max_length=100)),
                ('localizacao', models.CharField(blank=True, max_length=100)),
                ('codigo_qr', models.CharField(blank=True, max_length=200, unique=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('pre', 'Pré-cirurgia'), ('intra', 'Intraoperatório'), ('pos', 'Pós-cirurgia')], max_length=10)),
                ('paciente', models.CharField(blank=True, max_length=100)),
                ('cirurgia', models.CharField(blank=True, max_length=100)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('conferido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiais.kit')),
            ],
        ),
        migrations.CreateModel(
            name='LeituraQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('conferido', 'Conferido'), ('uso', 'Uso'), ('descartado', 'Descartado'), ('kit', 'Kit lido'), ('forasteiro', 'Item não previsto')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True)),
                ('checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materiais.checklist')),
                ('kit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materiais.kit')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materiais.material')),
            ],
        ),
        migrations.AddField(
            model_name='kit',
            name='materiais',
            field=models.ManyToManyField(to='materiais.material'),
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conferido', models.BooleanField(default=False)),
                ('data_conferencia', models.DateTimeField(blank=True, null=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiais.checklist')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiais.material')),
            ],
            options={
                'unique_together': {('checklist', 'material')},
            },
        ),
        migrations.AddField(
            model_name='checklist',
            name='materiais',
            field=models.ManyToManyField(through='materiais.ChecklistItem', to='materiais.material'),
        ),
    ]
