# Generated by Django 5.2.12 on 2026-03-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0003_add_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='fornecedor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='material',
            name='localizacao',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
