# Generated by Django 5.2.12 on 2026-03-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0004_alter_material_fornecedor_alter_material_localizacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklist',
            options={'ordering': ['-data_inicio']},
        ),
        migrations.AlterModelOptions(
            name='kit',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['nome']},
        ),
        migrations.AddField(
            model_name='checklist',
            name='paciente_nome',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='checklist',
            name='paciente_prontuario',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
