# Generated by Django 5.2.12 on 2026-03-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0005_alter_checklist_options_alter_kit_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
    ]
