# Generated by Django 5.2.12 on 2026-03-10 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0006_checklist_concluido'),
    ]

    operations = [
    ]
