# Generated by Django 5.2.12 on 2026-03-10 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0007_initial_kitpaciente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('prontuario', models.CharField(max_length=50, unique=True)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='checklist',
            options={'ordering': ['fase']},
        ),
        migrations.RenameField(
            model_name='checklist',
            old_name='data_fim',
            new_name='data_conclusao',
        ),
        migrations.AddField(
            model_name='checklist',
            name='itens',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='checklist',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='usuario_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='KitPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cirurgia', models.DateTimeField()),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('pre_operatorio', 'Pré-operatório'), ('intra_operatorio', 'Intra-operatório'), ('pos_operatorio', 'Pós-operatório'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='agendado', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiais.kit')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiais.paciente')),
            ],
            options={
                'ordering': ['-data_cirurgia'],
            },
        ),
        migrations.AddField(
            model_name='checklist',
            name='kit_paciente',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='materiais.kitpaciente'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='checklist',
            unique_together={('kit_paciente', 'fase')},
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='cirurgia',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='conferido_por',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='kit',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='materiais',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='paciente_nome',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='paciente_prontuario',
        ),
    ]
