# Generated by Django 5.2.12 on 2026-03-10 15:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0008_paciente_alter_checklist_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['nome'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='criado_em',
        ),
        migrations.AddField(
            model_name='paciente',
            name='data_importacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Data de importação do AGHU'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='fonte',
            field=models.CharField(default='LOCAL', help_text='Fonte dos dados (AGHU/LOCAL)', max_length=10),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nome_mae',
            field=models.CharField(default='Não informado', help_text='Nome completo da mãe', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(help_text='CPF do paciente', max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(help_text='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome',
            field=models.CharField(help_text='Nome completo do paciente', max_length=200),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='prontuario',
            field=models.CharField(help_text='Prontuário AGHU', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(blank=True, help_text='Telefone para contato', max_length=20, null=True),
        ),
    ]
